// Generated by https://quicktype.io

export interface Livro {
  id: number;
  ISBN: string;
  categoria: Categoria;
  preco: number;
  quantidade: number;
  autores: Autor[];
  editora: Editora;
}

export interface Categoria {
  id: number;
  nome: string;
}

export interface Autor {
  id: number;
  nome: string;
}

export interface Editora {
  id: number;
  nome: string;
  site: string;
}
